import { useCallback, useEffect, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, ExternalLink, RefreshCw, TriangleAlert } from "lucide-react";

import { AppShell } from "@/components/app-shell";
import { GenerateForm, type Prefill } from "@/components/generate-form";
import { PageHeader } from "@/components/page-header";
import { JobStatusBadge } from "@/components/phase-track";
import { RunTracker } from "@/components/run-tracker";
import { SlotBoard } from "@/components/slot-board";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { ApiError } from "@/lib/api";
import { safeHref } from "@/lib/utils";
import { getConfig, getJob, getJobs, getSlots } from "@/lib/generate";
import {
  blockedReason, elapsedText, pollDelay, type GenConfig, type GithubState, type Job, type Slot,
} from "@/lib/generate-format";
import { formatIST } from "@/lib/posts";

type Board = { now: string; slots: Slot[] };

function Skeletons() {
  return (
    <div className="grid gap-5" role="status" aria-label="Loading the Generate page">
      <Skeleton className="h-52 w-full" />
      <Skeleton className="h-64 w-full" />
    </div>
  );
}

function jobSummary(j: Job): string {
  if (j.topic_title) return j.topic_title;
  if (j.topic) return j.topic;
  return `Auto topic${j.category ? ` · ${j.category}` : ""}`;
}

function History({ jobs, onOpen }: { jobs: Job[]; onOpen: (j: Job) => void }) {
  if (!jobs.length) {
    return (
      <div className="grid gap-1 border-t border-dashed border-border pt-4">
        <p className="text-sm font-medium">No generation requests yet</p>
        <p className="max-w-prose text-sm text-muted-foreground">
          Posts are generated by the scheduler twice a day. Requests you start here, and scheduled runs, will be listed with their result.
        </p>
      </div>
    );
  }
  return (
    <ol className="grid divide-y overflow-hidden rounded-xl border bg-card/40">
      {jobs.map((j) => (
        <li key={j.id} className="grid gap-1.5 p-3 sm:grid-cols-[9.5rem_1fr_auto] sm:items-start sm:gap-4">
          <div className="flex items-center gap-2 sm:grid sm:gap-1">
            <JobStatusBadge status={j.status} className="w-fit" />
            <time dateTime={j.created_at} className="numeral text-xs text-muted-foreground">{formatIST(j.created_at)}</time>
          </div>
          <div className="min-w-0">
            <button type="button" onClick={() => onOpen(j)} className="rounded-[4px] text-left font-medium leading-snug break-words hover:text-primary focus-visible:text-primary">
              {jobSummary(j)}
            </button>
            <p className="mt-0.5 text-xs text-muted-foreground">
              <span className="font-mono">#{j.id}</span>{" · "}
              {j.trigger === "scheduled" ? "Scheduled" : `Dashboard · ${j.requested_by ?? "admin"}`}
              {j.slot_at ? ` · slot ${formatIST(j.slot_at, false)}` : ""}
              {j.force ? " · extra post" : ""}
              {j.status === "failed" || j.status === "skipped" || j.status === "cancelled" ? ` · ${j.message ?? j.failure_reason ?? ""}` : ""}
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-muted-foreground sm:justify-end">
            {j.duration_sec != null && <span className="tabular-nums">{elapsedText(j.duration_sec)}</span>}
            {j.post_ids[0] && <Link to={`/posts?post=${encodeURIComponent(j.post_ids[0])}`} className="inline-flex items-center rounded-[4px] text-primary underline-offset-2 hover:underline touch:min-h-11">Post</Link>}
            {safeHref(j.github_run_url, true) && (
              <a href={safeHref(j.github_run_url, true)} target="_blank" rel="noreferrer" className="inline-flex items-center gap-0.5 rounded-[4px] text-primary underline-offset-2 hover:underline touch:min-h-11">
                Run<ExternalLink className="size-3" aria-hidden /><span className="sr-only"> (opens in a new tab)</span>
              </a>
            )}
          </div>
        </li>
      ))}
    </ol>
  );
}

export default function Generate() {
  const [cfg, setCfg] = useState<GenConfig | null>(null);
  const [board, setBoard] = useState<Board | null>(null);
  const [jobs, setJobs] = useState<Job[]>([]);
  const [github, setGithub] = useState<GithubState>({ ok: true, as_of: new Date().toISOString() });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [updatedAt, setUpdatedAt] = useState<number | null>(null);
  const [now, setNow] = useState(() => Date.now());
  const [prefill, setPrefill] = useState<Prefill | null>(null);
  const [viewId, setViewId] = useState<string | null>(null);  // a past request picked from the list
  const abort = useRef<AbortController | null>(null);

  const refresh = useCallback(async () => {
    abort.current?.abort();
    const ctrl = new AbortController();
    abort.current = ctrl;
    try {
      const [c, b, j] = await Promise.all([getConfig(ctrl.signal), getSlots(ctrl.signal), getJobs(ctrl.signal)]);
      setCfg(c);
      setBoard(b);
      setJobs(j.jobs);
      setGithub(j.github);
      setUpdatedAt(Date.now());
      setError(null);
    } catch (e) {
      if ((e as Error).name === "AbortError") return;
      setError(e instanceof ApiError ? e.message : "Couldn't load the Generate page.");
    } finally {
      if (!ctrl.signal.aborted) setLoading(false);
    }
  }, []);

  useEffect(() => { refresh(); }, [refresh]);

  const active = jobs.find((j) => j.active) ?? null;
  const activeId = active?.id;

  // While a run is active, follow just that job every few seconds; otherwise reload everything once a minute.
  // Nothing polls while the tab is hidden, and coming back refreshes at once. A failed poll never breaks the page.
  useEffect(() => {
    let timer: ReturnType<typeof setTimeout> | undefined;
    let stopped = false;
    const tick = async () => {
      if (stopped) return;
      const delay = pollDelay(!!activeId, document.hidden, github.ok);
      if (delay === null) return;
      timer = setTimeout(async () => {
        try {
          if (activeId) {
            const r = await getJob(activeId);
            setGithub(r.github);
            setJobs((prev) => prev.map((j) => (j.id === r.job.id ? r.job : j)));
            if (!r.job.active) await refresh();
          } else {
            await refresh();
          }
        } catch {
          setGithub((g) => ({ ...g, ok: false }));
        }
        tick();
      }, delay);
    };
    const onVisible = () => {
      if (!document.hidden) { clearTimeout(timer); refresh().finally(tick); }
    };
    tick();
    document.addEventListener("visibilitychange", onVisible);
    return () => { stopped = true; clearTimeout(timer); document.removeEventListener("visibilitychange", onVisible); };
  }, [activeId, github.ok, refresh]);

  useEffect(() => {
    const t = setInterval(() => setNow(Date.now()), activeId ? 1000 : 30000);
    return () => clearInterval(t);
  }, [activeId]);

  const today = board?.slots.filter((s) => s.day === "today") ?? [];
  const tracked = active ?? jobs.find((j) => j.id === viewId) ?? jobs[0] ?? null;
  const blocked = cfg ? blockedReason(cfg, active, (iso) => `${formatIST(iso, false)} IST`) : null;
  const generated = today.filter((s) => s.state === "generated").length;
  const quotaOut = cfg?.quota_cooldown_until && new Date(cfg.quota_cooldown_until).getTime() > now;

  function retry(job: Job) {
    const time = job.slot_at ? formatIST(job.slot_at, false) : "";
    setPrefill({
      nonce: Date.now(),
      slot: cfg?.slots.includes(time) && today.some((s) => s.time === time) ? time : "auto",
      category: job.category ?? "auto", topic: job.topic ?? "", source_url: job.source_url ?? "",
    });
  }

  function pick(slot: Slot) {
    setPrefill({ nonce: Date.now(), slot: slot.time });
  }

  return (
    <AppShell>
      <div className="mx-auto grid max-w-[78rem] gap-7 px-4 py-6 md:px-8 md:py-9">
        <PageHeader
          index="03"
          eyebrow="Work order"
          title="Generate"
          lead={board ? `${generated} of ${today.length} slots generated today (IST). Nothing posts until you approve it.` : "Start a post and watch it get made."}
          meta={updatedAt && (
            <span className="font-mono text-[11px] text-muted-foreground tabular-nums">
              Updated {formatIST(new Date(updatedAt).toISOString(), false)} IST
            </span>
          )}
          actions={(
            <Button variant="outline" size="sm" onClick={() => { setLoading(true); refresh(); }}>
              <RefreshCw className={loading ? "animate-spin" : ""} />
              Refresh
            </Button>
          )}
        />

        {quotaOut && (
          <p role="status" className="flex gap-2 border-l-[3px] border-wait bg-wait/10 py-3 pr-4 pl-4 text-sm">
            <TriangleAlert className="mt-0.5 size-4 shrink-0 text-wait" aria-hidden />
            <span>
              Gemini&apos;s free quota ran out. It resets around 12:30 IST (midnight Pacific). New runs will probably fail until then.
            </span>
          </p>
        )}
        {cfg && !cfg.publishing_enabled && (
          <p className="text-xs text-muted-foreground">Publishing is turned off in this environment. Generating still works.</p>
        )}
        {error && <p role="alert" className="border-l-[3px] border-bad bg-bad/10 py-3 pr-4 pl-4 text-sm text-bad">{error}</p>}

        {loading && !cfg ? (
          <Skeletons />
        ) : cfg && board ? (
          <div className="grid items-start gap-x-10 gap-y-9 lg:grid-cols-[minmax(0,1fr)_23rem]">
            <div className="grid min-w-0 gap-5 lg:col-start-1 lg:row-start-1">
              {tracked ? (
                <RunTracker job={tracked} now={now} github={github} onRetry={retry} />
              ) : (
                <section className="grid justify-items-start gap-3 border-t border-dashed border-border py-10 sm:grid-cols-[auto_1fr] sm:gap-x-8" aria-labelledby="tracker-title">
                  <span aria-hidden className="font-heading text-7xl leading-none font-bold text-transparent [-webkit-text-stroke:1px_var(--rule)]">00</span>
                  <div className="grid content-center gap-1.5">
                    <h2 id="tracker-title" className="font-heading text-lg font-semibold">Nothing is running</h2>
                    <p className="max-w-prose text-sm text-muted-foreground">
                      When you start a run, its progress shows up here phase by phase, with a link to the GitHub run.
                    </p>
                    <Button variant="outline" size="sm" className="mt-2 w-fit touch:h-11" disabled={!!blocked} title={blocked ?? undefined}
                      onClick={() => setPrefill({ nonce: Date.now(), slot: "auto" })}>
                      Generate for the next slot<ArrowRight />
                    </Button>
                  </div>
                </section>
              )}
            </div>

            {/* Phone order: tracker, slots, form, history (the slot board answers "is today covered?" first). */}
            <section aria-labelledby="board-title" className="min-w-0 lg:col-start-1 lg:row-start-2">
              <h2 id="board-title" className="label-mono mb-4">Posting slots</h2>
              <SlotBoard
                slots={board.slots}
                lateLimit={cfg.late_limit_hours}
                onPick={pick}
                pickDisabled={blocked}
                picked={prefill?.slot ?? ""}
              />
            </section>

            <div className="min-w-0 lg:col-start-2 lg:row-span-3 lg:row-start-1">
              <GenerateForm
                cfg={cfg}
                slots={today}
                blocked={blocked}
                prefill={prefill}
                onRequested={(job) => { setViewId(null); setJobs((p) => [job, ...p.filter((j) => j.id !== job.id)]); refresh(); }}
                onActive={(job) => setJobs((p) => [job, ...p.filter((j) => j.id !== job.id)])}
                onRefresh={refresh}
              />
            </div>

            <section aria-labelledby="recent-title" className="min-w-0 lg:col-start-1 lg:row-start-3">
              <h2 id="recent-title" className="label-mono mb-3">Recent requests</h2>
              <History jobs={jobs} onOpen={(j) => { setViewId(j.id); window.scrollTo({ top: 0, behavior: "smooth" }); }} />
              <p className="mt-2 text-xs text-muted-foreground">
                Regenerating from feedback happens in <Link to="/posts" className="text-primary underline-offset-2 hover:underline">Posts</Link>. Times are IST.
              </p>
            </section>
          </div>
        ) : null}
      </div>
    </AppShell>
  );
}
