"""posts: group_id, targets, youtube overrides

Revision ID: 6ea71f245945
Revises: 006e3a58107d
Create Date: 2026-09-28 16:03:23.324108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ea71f245945'
down_revision: Union[str, Sequence[str], None] = '006e3a58107d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing rows: add with a default and backfill "<date>/<slug>" from post_dir. The default is
    # kept so code that predates group_id can still insert rows while this is rolled out.
    op.add_column('posts', sa.Column('group_id', sa.String(length=120), nullable=False, server_default=''))
    op.execute(r"""
        UPDATE posts
        SET group_id = COALESCE(substring(replace(post_dir, '', '/') from 'output/([^/]+/[^/]+)'),
                                to_char(date, 'YYYY-MM-DD') || '/' || id)
    """)
    op.add_column('posts', sa.Column('targets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('posts', sa.Column('yt_title', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('yt_description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_posts_group_id'), 'posts', ['group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_group_id'), table_name='posts')
    op.drop_column('posts', 'yt_description')
    op.drop_column('posts', 'yt_title')
    op.drop_column('posts', 'targets')
    op.drop_column('posts', 'group_id')
    # ### end Alembic commands ###
