import { useEffect, useState } from "react";
import { Link } from "react-router-dom";

import { getJobForGroup, type GroupJob } from "@/lib/generate";

/** "Generated by request #id" for a post group (nothing for posts made before requests were recorded). */
export function GeneratedBy({ groupId }: { groupId: string }) {
  const [job, setJob] = useState<GroupJob | null>(null);

  useEffect(() => {
    const ctrl = new AbortController();
    setJob(null);
    getJobForGroup(groupId, ctrl.signal).then((r) => setJob(r.job)).catch(() => {});
    return () => ctrl.abort();
  }, [groupId]);

  if (!job) return null;
  return (
    <span>
      {job.trigger === "scheduled" ? "Scheduled run " : "Generated by request "}
      <Link to={`/logs?q=${encodeURIComponent(job.id)}`} className="font-mono text-primary underline-offset-2 hover:underline">#{job.id}</Link>
      {job.trigger === "dashboard" && job.requested_by ? ` · ${job.requested_by}` : ""}
    </span>
  );
}
